### ISSUE TITLE
We need a logo!

### ISSUE THREAD

**Issue by macabeus** [macabeus/klo-gba.js#12]
Always nice projects have a nice visual identity. Then, we need a nice logo!

**Comment by GabrielaBezerra** [comment]
![rascunho_klonoa_gba](https://user-images.githubusercontent.com/17304151/54873546-de459700-4db6-11e9-824b-8f4137da0632.png)

Here is a Sketch of what the logo could be like. This was very roughly made with gimp, using only the trackpad. Maybe someone can work with better tools and improve this idea 😊

**Comment by Kniksisk** [comment]
![Klonoa_Logo_GBA](https://user-images.githubusercontent.com/31035821/55296048-c4c1d200-53ea-11e9-9eb5-512f3e00d133.jpg)

With the ideas of GabrielaBezerra I created the two forms of logo desigh for the project. The first is a beret used by Klonoa on Wii Remake and the second is the hat used on GBA and PS2. Give me hints of what I can improve.

**Comment by Kniksisk** [comment]
I started working on the project logotype.
![Untitled-1](https://user-images.githubusercontent.com/31035821/56374450-8fcec100-61d9-11e9-80ee-1f50ef9a0ff6.png)
In my first Sketches I answered what had been requested, write "Klo-GBA.JS" with the font of the Klonoa logo. I started with something of the mind, a quick sketch, unplanned, done in about 4 minutes. Then I decided to do something more worked, searching for the official angles and shapes, and with that result I made a modification in Photoshop to get an improved result with only "Ctrl + C, Ctrl + V".

So I started to vector.
<img width="1187" alt="1" src="https://user-images.githubusercontent.com/31035821/56378764-5f405480-61e4-11e9-9f98-87f6ee9e5456.png">
The first is based on the "Klonoa: Empire of Dreams" logo. The colors are the simplest, tetradic, being only 3. Using a strong yellow, almost orange, but a lighter blue than the ones used on the edges of the other logos below. The letters have pointed shapes, but different from the official logo here we have thick edges and rounded corners.
I particularly like this because it is inspired by the game logo that is the basis of the project.

<img width="1187" alt="2" src="https://user-images.githubusercontent.com/31035821/56379407-112c5080-61e6-11e9-82aa-68fc3b1edc06.png">
This second is my favorite, several interesting details have been added here. Inspired by the "Klonoa 2: Dream Champion Tournament", here we have the largest number of colors present. The yellow is light, having the source with sharp corners and a slight bevel. The blue of the "JS" is degrade, as is the "2" of the official logo. This same "JS" has an inner border with a small bevel, as if it were a small detail of jewelry, giving a highlight to the shape.
The phrase is separated by a "dot", being the only one different from the other logos, inspired by the "hyphen" of the second game of our "cabbit" for GBA.

<img width="1187" alt="3" src="https://user-images.githubusercontent.com/31035821/56379717-bf37fa80-61e6-11e9-9159-c5be257ff44c.png">
I love this third, although it was not my favorite for the project, it was very fun to do it. Clearly inspired by the "Klonoa 2: Lunatea's Veil" logo, with its rounded edges, beveled golden bevel at the contour and an obvious degrade with lighter colors at the top and darker at the bottom. Here it was possible to make the "J" follow the last part of the "A", and the "JS" is clearly highlighted in relation to the "Klo-GBA", with a degradation from yellow to orange.

<img width="1187" alt="4" src="https://user-images.githubusercontent.com/31035821/56379781-e5f63100-61e6-11e9-952c-640099629d70.png">
We arrived at the last logotype. Based on the one used in "Klonoa: Door to Phantomile" it is simple and objective. The yellow here is slightly orange, more than the first, but it has a more obvious bevelling of all, with a slight shadow projected on the blue border. He is faithfully inspired by the logo of the first game, and has a sense of nostalgia, different from all other, liked any other, many like it.

With all the logotypes presented I come here to ask the help of all to decide together which of them we should make official.

**Comment by otaviopace** [comment]
Opinions below:

I like this one:

![first-logo](https://user-images.githubusercontent.com/31035821/56378764-5f405480-61e4-11e9-9f98-87f6ee9e5456.png)

However I don't like that it is all yellow.

I like this one too:

![third-logo](https://user-images.githubusercontent.com/31035821/56379717-bf37fa80-61e6-11e9-9159-c5be257ff44c.png)

However I think this blue is too dark.

The one below is my favorite:

![favorite-logo](https://user-images.githubusercontent.com/31035821/56379407-112c5080-61e6-11e9-82aa-68fc3b1edc06.png)

This is all my opinio though. Put your thoughts!!!

**Comment by macabeus** [comment]
All these logos are **awesome**!! Very very thank you for the hard work to design it 😄

One of the most important factor to choice a logo is that it should be flexible to work very well in all situations (we don't want to have [the same problem that Slack had](https://slackhq.com/say-hello-new-logo), right?)

Then I made a simulation in these logos working at the site and the readme.

# readme

The **readme** is the first impression that many users will have about the project. Then a logo should can works very well in a readme, don't distracting the users in the reading and at a blank background.

<details>
<b>Klonoa: Empire of Dreams</b>
<img src="https://user-images.githubusercontent.com/9501115/56400720-c2090e80-622b-11e9-9603-49b99b4bd087.png">

<b>Klonoa 2: Dream Champion Tournament</b>
<img src="https://user-images.githubusercontent.com/9501115/56400996-24aeda00-622d-11e9-864b-bb1c5a60731e.png">

<b>Klonoa 2: Lunatea's Veil</b>
<img src="https://user-images.githubusercontent.com/9501115/56400779-085e6d80-622c-11e9-939a-d9398026597c.png">

<b>Klonoa: Door to Phantomile</b>
<img src="https://user-images.githubusercontent.com/9501115/56400905-b538ea80-622c-11e9-90b5-5766d8d33976.png">
</details>

Seeing these images, I think that the better approach are using **Klonoa: Empire of Dreams (first)** or **Klonoa 2: Dream Champion Tournament (second)** versions. These logos fits very well.

The border of **Klonoa 2: Lunatea's Veil (third)** isn't very well to this situation.
The **Klonoa: Door to Phantomile (fourth)** "draws a lot of attention", maybe because the color and the tips of the letters are very sharp with much shadow.

# site

Our **site** is the most important, because is where our user will see the logo for most part of the time, associating it to the product. Different of the readme, it should fit in a small place at the header

<details>
<b>Klonoa: Empire of Dreams</b>
<img src="https://user-images.githubusercontent.com/9501115/56401622-380f7480-6230-11e9-945a-a21ce694b5e2.png">

<b>Klonoa 2: Dream Champion Tournament</b>
<img src="https://user-images.githubusercontent.com/9501115/56401577-f8e12380-622f-11e9-9ce9-5fb644edee74.png">

<b>Klonoa 2: Lunatea's Veil</b>
<img src="https://user-images.githubusercontent.com/9501115/56401558-dc44eb80-622f-11e9-9112-1f2bca65313b.png">

<b>Klonoa: Door to Phantomile</b>
<img src="https://user-images.githubusercontent.com/9501115/56401668-65f4b900-6230-11e9-827c-33b1fd7fa8c2.png">
</details>

I like **Klonoa: Empire of Dreams**, because this logo is very simple. Since it has only three colors, it fit very well, don't distracting the user and will be very to create a new pallet for the site that fit with it. The **Klonoa: Door to Phantomile** is similar, but I still prefer the first, because I prefer a subtle shadow.

I also like **Klonoa 2: Dream Champion Tournament** version. Since it has more colors, would be nice to create a pallet with this blue, yellow and a little of green, but I think that will be harder.

I still don't like **Klonoa 2: Lunatea's Veil** because of the border too gross.

**Comment by Deivis** [comment]
In my opinion the following logo is the best because is simple and I liked the colors and contrast used.
![](https://user-images.githubusercontent.com/31035821/56378764-5f405480-61e4-11e9-9f98-87f6ee9e5456.png)
