### ISSUE TITLE
Project depends on Docker

### ISSUE THREAD

**Issue by vinibern5** [macabeus/klo-gba.js#5]
In order to execute the project, actually, you'll need to have docker installed on your machine since it uses it to compile the webassembly code.

Maybe we should put this as a dependency on the README, or compile the webassembly code without using docker at all.

**Comment by macabeus** [comment]
Yeah. We can write a hint it on second step, for example:
```
2 - At the project root, compile some webassembly running this command. You'll need Docker to run it.
```

Or, better: We can change the shellscript code to check if have Docker on the computer, to warning to install it if doesn't have it.

I don't like the idea to put the compiled webassembly on the repository, because this is a generated code. It could conflict very easily.

**Comment by vinibern5** [comment]
Agreed, I've added information about docker on the README. Check PR #8 
And yup, using docker is much easier to compile the webassembly stuff, since we could have some problems related to different SO's, etc.
